name: Atualiza Estatísticas GitHub

on:
  schedule:
    - cron: '0 2 * * *'  # executa todo dia às 2h da manhã (horário UTC)
  workflow_dispatch:     # permite rodar manualmente no GitHub

jobs:
  atualiza:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script Python
        run: python agregador.py

      - name: Commit e push dos resultados
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Atualização automática das estatísticas"
